# Reporte un file con observaciones y funcion import

importar librerias

In [6]:
import pandas as pd
import os
from files import *

obtener ruta de archivos

In [7]:
base_dir   = os.path.dirname(os.path.realpath('__file__'))
downloads  = os.path.join(base_dir, 'descargas')
list_files = os.listdir(downloads)
output     = os.path.join(base_dir, 'output')
exist      = os.path.exists(output)
if not exist:
    os.makedirs(output)

obtener ruta de observaciones

In [8]:
data_obs = pd.read_excel('observaciones.xls')
df_obs   = pd.DataFrame(data_obs)

llamar funcion iter generar el dataframe y guardar

In [9]:
df = pd.DataFrame(iter_files(list_files, df_obs, downloads))
hs = datetime.datetime.now()
filename = f'reporte{hs:%Y-%m-%d}'
df.to_excel(f"{output}\{filename}.xlsx", sheet_name='reporte', 
                columns=['fecha', 'entrada' ,'salida','hs_trab','observaciones'], 
               index=False, startrow = 2, header= False)

print

In [10]:
df.style.hide_columns(["nombre"]).hide_index()